name: Build and deploy Python app to Azure Web App - Neural-Nomads-hackathon-PRD-WA-UAEN-01

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FLASK_ENV: production
  PYTHON_VERSION: '3.10'
  WEBAPP_NAME: 'Neural-Nomads-hackathon-PRD-WA-UAEN-01'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install gunicorn

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Configure Azure Web App Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          general-settings-json: '{
            "linuxFxVersion": "python|3.10",
            "startupCommand": "gunicorn --bind=0.0.0.0 --timeout 600 --workers 4 --threads 2 app:app"
          }'
          app-settings-json: '{
            "SCM_DO_BUILD_DURING_DEPLOYMENT": "true",
            "WEBSITES_PORT": "8000",
            "FLASK_ENV": "production",
            "PYTHON_VERSION": "3.10",
            "CORS_ALLOWED_ORIGINS": "*"  # Change to your frontend URL in production
          }'

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FC8B4AE3D13D4D37A2D0B309E0081596 }}
