- name: Configure Azure Web App
  uses: azure/appservice-settings@v1
  with:
    app-name: ${{ env.WEBAPP_NAME }}
    general-settings-json: '{"linuxFxVersion": "python|3.10"}'  # Only this line is needed
    app-settings-json: '{
      "SCM_DO_BUILD_DURING_DEPLOYMENT": "true",
      "WEBSITES_PORT": "8000"
    }'
